import NavBar from '@/components/layouts/nav-bar'
import './globals.css'
import type { Metadata } from 'next'
import { Providers } from "./providers";
import { Inter } from 'next/font/google'
import { Button } from '@nextui-org/react';
import FloatingButton from '@/components/layouts/floating-button';
import FloatingNavigation from '@/components/layouts/floating-navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className='dark'>
            <body className={inter.className}>
                <Providers>
                    <NavBar />
                    <div className='p-4 md:p-8 max-w-7xl mx-auto'>{children}</div>
                    <FloatingButton />
                    <FloatingNavigation />
                </Providers>

            </body>
        </html>
    )
}
